import Head from "next/head";
import Layout from "../components/Layout";
import Languages from "../components/home/Languages";
import Header from "../components/home/Header";
import Positions from "../components/home/Positions";
import Cursor from "../components/home/Cursor";
import Projects from "../components/projects/Projects";
import ContactMe from "../components/contactMe/ContactMe";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cursor />
      {/* <Animate /> */}
      <Header />
      {/* <ContactMe /> */}
      <Positions />
      <Languages />
      <Projects />
      <ContactMe />
    </Layout>
  );
}
